/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2026-07-12 17:00:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    com.duskdev.skillhub.model.User user = (com.duskdev.skillhub.model.User) session.getAttribute("user");

    boolean isAdmin = user != null && "ADMIN".equals(user.getRole());

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"viewport\"\r\n");
      out.write("          content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <title>SkillHub Dashboard</title>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            background: #f8fafc;\r\n");
      out.write("            color: #0f172a;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar {\r\n");
      out.write("            height: 70px;\r\n");
      out.write("            padding: 0 35px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            background: #0f172a;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar h2 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar a {\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            background: #dc2626;\r\n");
      out.write("            padding: 10px 16px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 35px auto;\r\n");
      out.write("            padding: 0 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome {\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 25px;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            box-shadow: 0 8px 25px rgba(0, 0, 0, 0.06);\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome h1 {\r\n");
      out.write("            margin-top: 0;\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cards {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns:\r\n");
      out.write("                repeat(auto-fit, minmax(210px, 1fr));\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 25px;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            box-shadow: 0 8px 25px rgba(0, 0, 0, 0.06);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card h3 {\r\n");
      out.write("            margin-top: 0;\r\n");
      out.write("            color: #64748b;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card .count {\r\n");
      out.write("            font-size: 36px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info {\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            background: #eff6ff;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            color: #1e3a8a;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar\">\r\n");
      out.write("\r\n");
      out.write("    <h2>SkillHub Training Portal</h2>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (isAdmin) { 
      out.write("\r\n");
      out.write("    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/portal/courses\">\r\n");
      out.write("        Courses\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/portal/students\">\r\n");
      out.write("        Students\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/portal/trainers\">\r\n");
      out.write("        Trainers\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/portal/enrollments\">\r\n");
      out.write("        Enrollments\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/portal/attendance\">\r\n");
      out.write("        Attendance\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/logout\">\r\n");
      out.write("        Logout\r\n");
      out.write("    </a>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<main class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <section class=\"welcome\">\r\n");
      out.write("\r\n");
      out.write("        <h1>\r\n");
      out.write("            Welcome,\r\n");
      out.write("            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loggedUser.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("        </h1>\r\n");
      out.write("\r\n");
      out.write("        <p>\r\n");
      out.write("            Role:\r\n");
      out.write("            <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loggedUser.role}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("        <p>\r\n");
      out.write("            Manage SkillHub training operations through this portal.\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"cards\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <h3>Total Courses</h3>\r\n");
      out.write("            <div class=\"count\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseCount}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <h3>Total Students</h3>\r\n");
      out.write("            <div class=\"count\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studentCount}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <h3>Total Trainers</h3>\r\n");
      out.write("            <div class=\"count\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${trainerCount}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <h3>Total Enrolments</h3>\r\n");
      out.write("            <div class=\"count\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${enrollmentCount}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <h3>Total Attendance Records</h3>\r\n");
      out.write("            <div class=\"count\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${attendanceCount}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"info\">\r\n");
      out.write("        Application started at:\r\n");
      out.write("        <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationStartTime}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
